apiVersion: quota.openshift.io/v1
kind: ClusterResourceQuota
metadata:
  name: clusterquota-andrew
spec:
  quota:
    hard:
      configmaps: "25"
      limits.cpu: "25"
      limits.memory: 40Gi
      persistentvolumeclaims: "25"
      pods: "25"
      requests.cpu: "5"
      requests.memory: 6Gi
      services: "25"
  selector:
    annotations:
      openshift.io/requester: andrew
