apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "3scale-resource-limits"
spec:
  limits:
    - type: "Pod"
      max:
        cpu: "4"
        memory: "2Gi"
      min:
        cpu: "50m"
        memory: "5Mi"
    - type: "Container"
      max:
        cpu: "4"
        memory: "2Gi"
      min:
        cpu: "50m"
        memory: "150Mi"
      default:
        cpu: "50m"
        memory: "150Mi"
      defaultRequest:
        cpu: "50m"
        memory: "150Mi"
# oc create -f core-resource-limits.yaml -n test-hpa
