apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "3scale-resource-limits"
spec:
  limits:
    - type: "Pod"
      max:
        cpu: "6"
        memory: "2Gi"
      min:
        cpu: "100m"
        memory: "150Mi"
    - type: "Container"
      max:
        cpu: "6"
        memory: "2Gi"
      min:
        cpu: "100m"
        memory: "150Mi"
      default:
        cpu: "100m"
        memory: "150Mi"
      defaultRequest:
        cpu: "100m"
        memory: "150Mi"
# oc create -f 14_limitrange.yaml
